// Auto-generated by build-org-logos.js
export const orgLogos: Record<string, string | null> = {
  "Metropolitan Atlanta Rapid Transit Authority": "/logos/marta.png",
  "MARTA": "/logos/marta.png",
  "CobbLinc (Cobb County Transit)": "/logos/cobblinc.png",
  "CobbLinc": "/logos/cobblinc.png",
  "Cobb County Transit": "/logos/cobblinc.png",
  "COBBLINC": "/logos/cobblinc.png",
  "Gwinnett County Transit": "/logos/ridegwinnett.png",
  "Ride Gwinnett": "/logos/ridegwinnett.png",
  "GCT": "/logos/ridegwinnett.png",
  "Clayton County Transit / CCT": null,
  "Clayton County Transit": null,
  "CCT": null,
  "Henry County Transit / local providers": null,
  "Henry County Transit": null,
  "Henry Transit": null,
  "Henry County local providers": null,
  "Board of Commissioners": null,
  "BeltLine Rail Now!": "/logos/beltlinerailnow.png",
  "A Better Cobb": "/logos/abettercobb.png"
  ,"Let's Propel ATL": "/logos/letspropelatl.png"
  ,"Lets Propel ATL": "/logos/letspropelatl.png"
  ,"MARTA Army": "/logos/martaarmy.png"
  ,"MARTAA rmy": "/logos/martaarmy.png"
  ,"MARTAArmy": "/logos/martaarmy.png"
};
