// Auto-generated by build-org-logos.js
export const orgLogos: Record<string, string | null> = {
  "Metropolitan Atlanta Rapid Transit Authority": "/logos/marta.svg",
  "MARTA": "/logos/marta.svg",
  "CobbLinc (Cobb County Transit)": "/logos/cobblinc.svg",
  "CobbLinc": "/logos/cobblinc.svg",
  "Cobb County Transit": "/logos/cobblinc.svg",
  "COBBLINC": "/logos/cobblinc.svg",
  "Gwinnett County Transit": "/logos/ridegwinnett.svg",
  "Ride Gwinnett": "/logos/ridegwinnett.svg",
  "GCT": "/logos/ridegwinnett.svg",
  "Clayton County Transit / CCT": null,
  "Clayton County Transit": null,
  "CCT": null,
  "Henry County Transit / local providers": null,
  "Henry County Transit": null,
  "Henry Transit": null,
  "Henry County local providers": null,
  "Board of Commissioners": null,
  "BeltLine Rail Now!": "/logos/beltlinerailnow.svg",
  "A Better Cobb": "/logos/abettercobb.svg"
};
